---
# cockpit/defaults/main.yml
cockpit_yum_pkgs:
    - npm
    - python-libguestfs
    - qemu
    - qemu-kvm
    - python
    - libvirt-client
    - openssl
    - libguestfs-tools
    - krb5-workstation
    - expect
    - rsync
    - libvirt-python
    - curl
    - xz

fed_pkgs:
  - python2-pbr

centos_pkgs:
  - python-pbr

rhel_pkgs:
  - python-pbr

cockpit_repo: https://github.com/cockpit-project/cockpit.git